DROP TABLE Guide CASCADE CONSTRAINTS;
DROP TABLE Vehicle CASCADE CONSTRAINTS;
DROP TABLE Tour CASCADE CONSTRAINTS;
DROP TABLE Location CASCADE CONSTRAINTS;
DROP TABLE Traveling CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE TravelingWith CASCADE CONSTRAINTS;
DROP TABLE BookedTour CASCADE CONSTRAINTS;
DROP TRIGGER PDate;
DROP TRIGGER CheckBus;
DROP TRIGGER SeniorSalary;
DROP TRIGGER NoDoubleShift;

DROP TABLE Customer CASCADE CONSTRAINTS;
DROP PROCEDURE DelCustomer;
DROP FUNCTION MinAge;
